import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
import Link from "next/link";
import { redirect } from "next/navigation";

import hero from "/public/hero.png";

import { Button } from "@/components/ui/button";
import ExplainerSection from "@/components/ExplainerSection";
import PricingSection from "@/components/PricingSection";

export const dynamic = "force-dynamic";

export default async function Index() {
  const supabase = createServerComponentClient({ cookies });

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (user) {
    return redirect("/overview");
  }


  return (
    <div className="flex flex-col items-center pt-16 bg-[#121212] text-[#E0E0E0] min-h-screen">
      <div className="flex flex-col lg:flex-row items-center gap-12 p-8 max-w-7xl w-full">
        <div className="flex flex-col space-y-6 lg:w-1/2 w-full">
          <h1 className="text-6xl font-extrabold leading-tight text-transparent bg-clip-text bg-gradient-to-r from-[#76e0f7] to-[#d783ff]">
            Professional AI Headshots in minutes.
          </h1>
          <p className="text-lg text-[#A0A0A0]">
            Elevate your online presence with HD headshots generated by our AI. Ideal for social profiles, resumes, and professional portfolios.
          </p>
          <div className="flex flex-col space-y-4">
            <Link href="/login">
            
                <Button className="w-full lg:w-auto px-8 py-3 bg-gradient-to-r from-[#667eea] to-[#764ba2] hover:from-[#764ba2] hover:to-[#667eea] transition-colors duration-300 ease-in-out transform hover:-translate-y-1">
                  Get Your Headshots
                </Button>
              
            </Link>
            <p className="text-sm text-[#A0A0A0] italic">
              Trusted by professionals worldwide. Quick and efficient.
            </p>
          </div>
          <div className="text-[#A0A0A0] mt-4">
            <span>Already a member? </span>
            <Link href="/login"
              className="text-[#76e0f7] hover:text-[#d783ff] transition-colors duration-300 ease-in-out">
                Sign In
            </Link>
          </div>
        </div>
        <div className="lg:w-1/2 w-full mt-8 lg:mt-0">
          <img
            src={hero.src}
            alt="AI Headshot Illustration"
            className="rounded-lg object-cover w-full h-full shadow-lg"
          />
        </div>
      </div>
      <ExplainerSection />
      <PricingSection />
    </div>
  );
}
