

import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
import Link from "next/link";
import { redirect } from "next/navigation";

import hero from "/public/hero2.webp";
import ExplainerSection from "@/components/ExplainerSection";
import PricingSection from "@/components/PricingSection";
import Image from "next/image";
import { imageData } from "@/lib/galleryData";

import { Testimonials } from "@/components/Testimonials";

export const dynamic = "force-dynamic";

const logos = [
  { src: '/fortune500-logos/001.png', width: 128, height: 64 },
  { src: '/fortune500-logos/016.png', width: 128, height: 64 },
  { src: '/fortune500-logos/028.png', width: 128, height: 64 },
  { src: '/fortune500-logos/032.png', width: 128, height: 64 },
  { src: '/fortune500-logos/033.png', width: 128, height: 64 },
  { src: '/fortune500-logos/081.png', width: 128, height: 64 },
  { src: '/fortune500-logos/083.png', width: 128, height: 64 },
  { src: '/fortune500-logos/443.png', width: 128, height: 64 },
  { src: '/fortune500-logos/187.png', width: 128, height: 64 },
  { src: '/fortune500-logos/264.png', width: 128, height: 64 },
  { src: '/fortune500-logos/267.png', width: 128, height: 64 },
  { src: '/fortune500-logos/286.png', width: 128, height: 64 },

  // Add more logos here
];

const imageUrl = "https://photoai.com/cdn-cgi/image/format=jpeg,fit=cover,width=768,height=1152,quality=75/https://r2-us-west.photoai.com/1706661114-6ace0ed476eb32dd8e5f7c36b5af1949-2.jpg";
const allUrls = Object.values(imageData.images).flatMap(imagePack => imagePack.urls);
const shuffledUrls = allUrls.sort(() => 0.5 - Math.random());
let selectedUrls = shuffledUrls.slice(0, 38);


export default async function Index() {
  const supabase = createServerComponentClient({ cookies });

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (user) {
    return redirect("/overview");
  }




  return (
    <div className="flex flex-col items-center text-[#E0E0E0] min-h-screen">
      <div className="p-6 max-w-7xl w-full">
        {/* Hero Section with Gradient Background */}
        <section className="flex flex-col items-center gap-8 text-center pt-8 pb-16 relative after:content-[''] after:absolute after:inset-x-0 after:bottom-0 after:h-32 after:bg-gradient-to-t after:from-[#121212] after:to-transparent">
          <h1 className="text-4xl md:text-6xl font-extrabold leading-tight bg-clip-text text-transparent bg-gradient-to-r from-blue-400 to-purple-500">
            Professional AI Headshots in Minutes
          </h1>
          <p className="text-lg md:text-xl max-w-3xl mx-auto text-gray-300">
            Elevate your online presence with HD headshots generated by our AI. Perfect for social profiles, resumes, and professional portfolios.
          </p>
          <div className="space-y-4 sm:space-y-0 sm:flex sm:gap-6 sm:justify-center">
            <Link href="/login" className="bg-gradient-to-r from-purple-500 to-pink-500 hover:bg-gradient-to-l text-white font-semibold py-2 px-4 md:px-8 rounded-lg shadow-lg transition-transform hover:-translate-y-1 hover:scale-105">
              Get Your Headshots
            </Link>
            <p className="text-sm text-gray-400 italic max-w-xs mx-auto sm:mx-0">
              Trusted by professionals worldwide. Quick and efficient.
            </p>
          </div>
          <div className="text-sm text-gray-400 z-30">
            Already a member?{" "}
            <Link href="/login" className="text-blue-300 hover:text-blue-500 transition-colors cursor-pointer">
              Sign In
            </Link>
          </div>
        </section>

        {/* Premium Headshot Collections with Blur Blend Effect */}
        <section className="px-4 py-8 lg:py-16 relative w-full rounded-md z-10 bg-gradient-to-b from-transparent via-[#343434] to-transparent">
          <h2 className="text-3xl lg:text-5xl font-bold text-center mb-8 lg:mb-16 shadow-2xl bg-clip-text text-transparent bg-gradient-to-r from-pink-500 via-purple-500 to-indigo-500 antialiased">
            Premium Headshot Collections
          </h2>

          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-4">
            {selectedUrls.map((imageUrl: string, index: number) => (
              <div className={`transform hover:scale-110 hover:z-10 transition duration-300 ease-out ${index % 2 ? "lg:translate-y-1/4" : "lg:translate-y-0"} overflow-hidden rounded-lg shadow-lg group`} key={index}>
                <img
                  className="w-full h-auto object-cover rounded-lg transition-all duration-300 ease-in-out group-hover:opacity-95"
                  src={imageUrl} alt={`Image ${index + 1}`}
                  width={768}
                  height={1152}
                />
              </div>
            ))}
          </div>
        </section>

        {/* Testimonials Section */}
        <section className="bg-black/80 mt-16 rounded-xl overflow-hidden">
          <Testimonials />
        </section>

        {/* Trusted by Leading Professionals */}
        <section className="my-16 py-8 rounded-xl overflow-hidden shadow-lg border border-gray-800">
          <h2 className="text-4xl font-bold text-center text-white mb-12">
            Trusted by Leading Professionals
          </h2>
          <div className="flex overflow-x-auto p-4">
            <div className="flex gap-4 snap-x snap-mandatory animate-slide logos-slide">
              {logos.map((logo, index) => (
                <div
                  key={index}
                  className="snap-center shrink-0 first:pl-10 last:pr-10"
                  style={{ filter: "brightness(100%)" }}>
                  <img
                    src={logo.src}
                    alt={`Logo ${index + 1}`}
                    className="h-12 md:h-16 object-contain"
                  />
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Explainer & Pricing Sections */}
        <ExplainerSection />
        <PricingSection />


      </div>
    </div>
  );

}
