import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
import Link from "next/link";
import { redirect } from "next/navigation";

import hero from "/public/hero2.webp";
import ExplainerSection from "@/components/ExplainerSection";
import PricingSection from "@/components/PricingSection";
import Image from "next/image";
import { imageData } from "@/lib/galleryData";

import { Testimonials } from "@/components/Testimonials";

export const dynamic = "force-dynamic";

const logos = [
  { src: '/fortune500-logos/001.png', width: 128, height: 64 },
  { src: '/fortune500-logos/016.png', width: 128, height: 64 },
  { src: '/fortune500-logos/028.png', width: 128, height: 64 },
  { src: '/fortune500-logos/032.png', width: 128, height: 64 },
  { src: '/fortune500-logos/033.png', width: 128, height: 64 },
  { src: '/fortune500-logos/081.png', width: 128, height: 64 },
  { src: '/fortune500-logos/083.png', width: 128, height: 64 },
  { src: '/fortune500-logos/443.png', width: 128, height: 64 },
  { src: '/fortune500-logos/187.png', width: 128, height: 64 },
  { src: '/fortune500-logos/264.png', width: 128, height: 64 },
  { src: '/fortune500-logos/267.png', width: 128, height: 64 },
  { src: '/fortune500-logos/286.png', width: 128, height: 64 },

  // Add more logos here
];

const imageUrl = "https://photoai.com/cdn-cgi/image/format=jpeg,fit=cover,width=768,height=1152,quality=75/https://r2-us-west.photoai.com/1706661114-6ace0ed476eb32dd8e5f7c36b5af1949-2.jpg";
const allUrls = Object.values(imageData.images).flatMap(imagePack => imagePack.urls);
const shuffledUrls = allUrls.sort(() => 0.5 - Math.random());
let selectedUrls = shuffledUrls.slice(0, 38);


export default async function Index() {
  const supabase = createServerComponentClient({ cookies });

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (user) {
    return redirect("/overview");
  }




  return (
    <div className="flex flex-col items-center md:pt-16 bg-[#121212] text-[#E0E0E0] min-h-screen rounded-lg">
      <div className="flex flex-col items-center gap-10 p-6 max-w-7xl mx-auto">
        <div className="text-center space-y-6 w-full">
          <h1 className="text-4xl md:text-6xl font-extrabold leading-tight text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-500">
            Professional AI Headshots in Minutes
          </h1>
          <p className="text-lg md:text-xl text-gray-300">
            Elevate your online presence with HD headshots generated by our AI. Perfect for social profiles, resumes, and professional portfolios.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
            <Link href="/login"
              className="inline-block bg-gradient-to-r from-purple-500 to-pink-500 hover:from-pink-500 hover:to-purple-500 text-white font-semibold py-3 px-6 md:px-10 rounded-lg shadow transform hover:-translate-y-1 transition-all duration-300">
              Get Your Headshots

            </Link>
            <p className="text-sm text-gray-400 italic">
              Trusted by professionals worldwide. Quick and efficient.
            </p>
          </div>
          <div className="text-gray-400 mt-4">
            <span>Already a member? </span>
            <Link href="/login"
              className="text-blue-300 hover:text-blue-400 transition-colors duration-300">
              Sign In

            </Link>
          </div>
        </div>
        <div className="w-full mt-12">
          <img
            src={hero.src}
            alt="AI Headshot Illustration"
            className="rounded-lg object-cover w-full max-h-96 shadow-xl"
            style={{ filter: 'brightness(90%)' }} // Adjust image brightness for better visibility of text overlay if necessary
          />
        </div>
      </div>





      <div className="bg-black/80 mt-16 border-t border-b border-primary rounded-xl">

        <Testimonials />


      </div>

      <div className="m-10 w-4/5 py-3 rounded-xl overflow-hidden shadow-lg border border-gray-800">
        <h2 className="text-4xl font-bold text-center text-white mb-12">
          Trusted by Leading Professionals
        </h2>
        <div className="flex overflow-x-auto scrollbar-hide p-4">
          <div className="logos-slide animate-slide flex flex-nowrap lg:ml-40 md:ml-20 ml-10 ">
            {logos.map((logo, index) => (
              <div
                key={index}
                className="inline-flex justify-center items-center p-4 min-w-[160px] hover:scale-105 transition-transform duration-300 ease-in-out"
                style={{ filter: "brightness(100%)" }}>
                <Image
                  src={logo.src}
                  alt={`Logo ${index + 1}`}
                  width={logo.width / 1.5}
                  height={logo.height / 1.5}
                  layout="intrinsic"
                  className="object-contain"
                />
              </div>
            ))}
          </div>
        </div>
      </div>

    





      <ExplainerSection />
      <PricingSection />

      <div className="w-full lg:w-screen px-4 py-8 relative">
        <h2 className="text-4xl font-bold text-center text-white mb-12">
          Popular Headshot Collections
        </h2>
        <div className="grid grid-cols-2 sm:grid-cols-4 md:grid-cols-6 lg:grid-cols-8 gap-2">
          {selectedUrls.map((imageUrl: string, index: number) => (
            <div className={`transform hover:scale-105 hover:rotate-2 hover:brightness-125 hover:ring-gray-500 ring ring-gray-950 ${index % 2 ? "translate-y-1/2" : "translate-y-0"} overflow-hidden rounded-lg shadow-lg relative`} key={index}>
              <img className="w-full h-full object-contain rounded-lg transition duration-150 ease-in-out opacity-70 hover:opacity-100" src={imageUrl} alt="Image description" />
            </div>
            
          ))}
        </div>
      </div>

    </div>
  );
}
